server:
  port: 8081
  servlet:
    context-path: /profile


spring:
  application:
    name: profile-service
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
